# Generated by Django 5.1.4 on 2024-12-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobantPokeBerries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokeberry",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
